# Generated by Django 5.2.1 on 2025-06-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post_id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='main.ideapost'),
            preserve_default=False,
        ),
    ]
