# Generated by Django 5.2.1 on 2025-06-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideapost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
